### ISSUE TITLE
Create equipment inventory to track SIMs and dongles

### ISSUE THREAD

**Issue by caromelendezl** [CodeYourFuture/glasgow-volunteer-planning#14]
@ClaireBickley will post if dongles get cancelled because of lack of system for tracking who has them. 

Will need to ask students to email task lead with sim/product numbers of items.

Can be structured similar to UK Laptop Inventory: [https://docs.google.com/spreadsheets/d/1QeZmhAKSD8k4lyIpWrZvZM3voWKf9rnSpI0WpcJIDLg/edit#gid=484306581 - Connect to preview](https://docs.google.com/spreadsheets/d/1QeZmhAKSD8k4lyIpWrZvZM3voWKf9rnSpI0WpcJIDLg/edit#gid=484306581)

UPDATE 06/01/2023

At KPC 5 dongles + one empty box and no sim cards

**Comment by emcglackenr1** [comment]
Relevant Extract from Gianluca meeting 16/12/2022

**_How were you managing the Vodafone dongles?_**
Gianluca reply:

There was a general issue of tracking equipment, have a better system with laptops
Some students may have a dongle right now, unsure where that info is
Dongles are for Trainees and Classes.
o He guessed about 3 are for classes
o Needed that to supplement the wifi at KPC, although it's possibly not an issue anymore
o Currently Paying for about 8 plans with Vodafone business account

@caromelendezl or @emcglackenr1 have to call them if we want to change this. Might not be necessary.

**Comment by emcglackenr1** [comment]
Dongles To do:

- [ ] Gather information about current dongles
- [ ] Determine necessity considering KPC refurbishment[ (related card)](https://github.com/CodeYourFuture/glasgow-class-6/issues/51)
- [ ] Compile inventory of dongles

**Comment by emcglackenr1** [comment]
ClaireBickley will post if dongles get cancelled because of lack of system for tracking who has them.
