### ISSUE TITLE
Organise new meeting times

### ISSUE THREAD

**Issue by caromelendezl** [CodeYourFuture/glasgow-volunteer-planning#19]
Update:

It was discussed that two volunteer meetings a week would be better. One for the Kanban and one for class planning. 

- [ ] @emcglackenr1 to create a poll for both days. Tues/Wed for Class Planning , Thurs/Fri for Kanban.

**Comment by sztupy** [comment]
Poll has been conducted, and so far Friday 5.30pm is the best, but need to revisit the poll

**Comment by emcglackenr1** [comment]
17.00-18.00 new time based on poll
