### ISSUE TITLE
Viewable List of Volunteers with Community Safety Training

### ISSUE THREAD

**Issue by caromelendezl** [CodeYourFuture/glasgow-volunteer-planning#20]
For Community Safety purposes, it is important to have a list of Active Volunteers who have undergone the training. Volunteers must have undergone safeguarding training in order to interact with trainees. 

Dara-Emma McG - 20/12/2022
- Clarification was requested on what Safeguarding meant. It is now renamed Community Safety [Relevant issue on clarification.](https://github.com/CodeYourFuture/glasgow-class-6/issues/21)
- Volunteers to undergo training [relevant issue](https://github.com/CodeYourFuture/glasgow-class-6/issues/35)

**Comment by emcglackenr1** [comment]
Elizabeth/Alec have the names of individuals who have undergone training so far. 
<h3>**_Anyone who is still to undergo training, please get in touch with Elizabeth. She conducts them on Tuesdays evenings._** <h3>

**Comment by emcglackenr1** [comment]
Elizabeth and Alec have this data from forms and applications to train. Dara to update list and manage data. Waiting on data updates from other CYF staff.
