### ISSUE TITLE
Clarify safeguarding further (NOW CALLED COMMUNITY SAFETY TRAINING)

### ISSUE THREAD

**Issue by caromelendezl** [CodeYourFuture/glasgow-volunteer-planning#21]
Greg expressed concern in Scot Volunteer meeting on 24/11 that he had concerns about the definition of vulnerable adults and what volunteer responsibilities are regarding reporting.

**_Dara Update from 16/12/2022_**
CYF staff currently working on clarification. Now called Community Safety Training to encompass more aspects of safety, such as GDPR, and reduce confusion. **Volunteers were unclear if term 'Safeguarding' implied responsibility of care. It does not.**

- List is being compiled of volunteers who have this training [Relevant issue on list.](https://github.com/CodeYourFuture/glasgow-class-6/issues/20)
- Volunteers to undergo training [relevant issue](https://github.com/CodeYourFuture/glasgow-class-6/issues/35)

**Comment by emcglackenr1** [comment]
CYF staff currently working on clarification and development of documents regarding this.

**Comment by sztupy** [comment]
We will have an ongoing weekly training on this

**Comment by emcglackenr1** [comment]
@caromelendezl to post link to the updated information regarding this

**Comment by emcglackenr1** [comment]
[Powerpoint presentation about it in resources tab](https://github.com/orgs/CodeYourFuture/projects/27/views/1?pane=issue&itemId=16727105)
