### ISSUE TITLE
Volunteers to Undergo Community Safety/Safeguarding Training (weekly Tuesday meeting)

### ISSUE THREAD

**Issue by caromelendezl** [CodeYourFuture/glasgow-volunteer-planning#35]
[Current list](
https://github.com/orgs/CodeYourFuture/projects/27/views/1?filterQuery=safety&pane=issue&itemId=16727105)

**Comment by emcglackenr1** [comment]
Dara-Emma McGR [20 Dec at 19:33]
Elizabeth is running weekly meetings. Please contact her for details. 
It is now called Community Safety training. See this kanban issue

Dara-Emma McGR [09 Dec at 18:30]
As per other Kanban item, Elizabeth has a list of who has completed this. Elisabeth and Alec are in charge of this. 
I have to wait for them to pass this information to me. 

Dara-Emma McGR [24 Nov at 18:23]
It has started running. Elizabeth runs this weekly on a Tuesday.

- - List is being compiled of volunteers who have this training [Relevant issue on list.](https://github.com/CodeYourFuture/glasgow-class-6/issues/20)
- Clarification was requested on what Safeguarding meant. It is now renamed Community Safety [Relevant issue on clarification.](https://github.com/CodeYourFuture/glasgow-class-6/issues/21)

**Comment by emcglackenr1** [comment]
@caromelendezl
