### ISSUE TITLE
End of Year CYF Community Gathering 17/12/2022

### ISSUE THREAD

**Issue by caromelendezl** [CodeYourFuture/glasgow-volunteer-planning#9]
**_POSTPONED_** **_See comment 15/12/2022_**

Probably a short evening event

**UPDATE 15/12/2022**

- Day/event start --> Saturday 14th January at 17.00 hrs 
- Day/event end --> Saturday 14th January at 21.00 hrs
- Location --> Kinning Park Complex

Contact Caro if you would like to help/contribute

Alastair: maybe some multiplayer gaming / similar

**Comment by msimmdev** [comment]
UPDATE from Caro (_in italic below_)
- Kinning park is available needs a time from the community
   _17.00 - 21.00 has been agreed_

- Certain times may need child-care or could advise trainees that they can bring their children as it's not a class. Caro to check if the children attending is OK 
   _It is ok to bring children to the Community Event. Every parent is responsible for them of course._ 

- Complex has a projector, could use this to arrange a pop quiz or similar.
   _We have access to the projector, speakers and mic. No Problem_

- If someone has a console to bring for games, this could be used as well.
   _No one has offered it yet. I will send a message to volunteers asking for help for the day and will mention this as well_

- For food could ask Volunteers to bring food or Caro could buy food in.
   _Caro will donate the food and drinks for this activity. Including Vegan, Gluten-free and Vegan options (maybe Halal but I'll need help with what will be appropriate as I don't know)_

- Drinks: Caro to check policy for alcoholic drinks. Need to be careful with alcohol around children.
   _Check with the global team, it is not an issue_

**Comment by emcglackenr1** [comment]
[Community Gathering was postponed until January ](https://github.com/CodeYourFuture/glasgow-class-6/issues/47)due to issues such as weather and transport strikes. It was considered more important that the event is accessible to as much of the community as possible.

**Comment by caromelendezl** [comment]
Update
